os: osx
osx_image: xcode9.3beta

env:
  global:
    - BUILD_CCACHE_DIR=~/build/ccache
    - BUILD_NINJA_DIR=~/build/ninja
  matrix:
    - PYTHON_VERSION=python2
    - PYTHON_VERSION=python3

before_install:
  - ./travis/before_install.sh

install:
  - ./travis/install.sh

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

after_failure:
  - ./travis/after_failure.sh

cache:
  - timeout: 300
  - directories:
    - $BUILD_CCACHE_DIR
    - $BUILD_NINJA_DIR
    - $HOME/.ccache
    - $HOME/.cache/pb
